/**
 * THE BOMBING OF DARWIN — HISTORICAL SPATIAL ENGINE
 * Spatial Configuration & Demonstration States
 * 
 * Defines the 4 contemporary geographic orientation states for Stage 1.
 * Geographically verified coordinates only — no fabricated historical attack lines.
 * References canonical location entities under data/entities/locations.json.
 */

import type { SpatialDemonstrationState, SpatialDemonstrationStateId } from './spatial-types';

export const DEMONSTRATION_STATES: Record<SpatialDemonstrationStateId, SpatialDemonstrationState> = {
  STATE_00_WORLD: {
    id: 'STATE_00_WORLD',
    index: 0,
    code: '00',
    label: 'World Context',
    geographicScope: 'Australia & Indo-Pacific',
    purpose: 'Orient the visitor globally. Establishes Australia in a restrained world context without bright satellite aesthetics or tourism chrome.',
    temporalContext: 'CONTEMPORARY',
    desktopCamera: {
      latitude: -23.5,
      longitude: 130.0,
      altitudeM: 9500000,
      headingDeg: 0,
      pitchDeg: -88,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -23.0,
      longitude: 132.0,
      altitudeM: 11200000,
      headingDeg: 0,
      pitchDeg: -89,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -28.5,
      longitude: 134.0,
      altitudeM: 13800000,
      headingDeg: 0,
      pitchDeg: -88,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -23.5,
      longitude: 129.0,
      altitudeM: 9800000,
      headingDeg: 0,
      pitchDeg: -88,
      rollDeg: 0,
    },
    durationMs: 2600,
    classification: 'ESTABLISHED_FACT',
    confidence: 'VERIFIED',
    notes: 'Contemporary global continental orientation. No historical claims.',
    humanClassification: 'Contemporary Geographic Reality',
    humanConfidence: 'Geodetically Verified',
    sourceInstitutions: ['Geoscience Australia', 'Commonwealth of Australia'],
    evidentialNuance: 'Contemporary global continental orientation. No historical claims.',
  },

  STATE_01_NORTH: {
    id: 'STATE_01_NORTH',
    index: 1,
    code: '01',
    label: 'Northern Australia',
    geographicScope: 'Top End & Maritime Approaches',
    purpose: 'Establish Darwin’s geographic position at the northern frontier of the continent, facing the Timor and Arafura Seas.',
    canonicalLocationEntityId: 'NORTHERN_TERRITORY_COAST_CONTEMPORARY',
    temporalContext: 'CONTEMPORARY',
    desktopCamera: {
      latitude: -13.2,
      longitude: 129.2,
      altitudeM: 1650000,
      headingDeg: 358,
      pitchDeg: -78,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -13.1,
      longitude: 130.0,
      altitudeM: 1950000,
      headingDeg: 358,
      pitchDeg: -79,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -15.8,
      longitude: 131.0,
      altitudeM: 2450000,
      headingDeg: 358,
      pitchDeg: -78,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -13.2,
      longitude: 129.5,
      altitudeM: 1750000,
      headingDeg: 358,
      pitchDeg: -78,
      rollDeg: 0,
    },
    durationMs: 2400,
    classification: 'ESTABLISHED_FACT',
    confidence: 'VERIFIED',
    notes: 'Contemporary geographic orientation of Northern Territory coastline.',
    humanClassification: 'Contemporary Geographic Reality',
    humanConfidence: 'Geodetically Verified',
    sourceInstitutions: ['Australian Hydrographic Office', 'Geoscience Australia'],
    evidentialNuance: 'Contemporary coastal geography of the Top End and maritime approaches.',
  },

  STATE_02_DARWIN: {
    id: 'STATE_02_DARWIN',
    index: 2,
    code: '02',
    label: 'Darwin & Coastline',
    geographicScope: 'Beagle Gulf & Harbour Peninsulas',
    purpose: 'Reveal Darwin and its relationship to the coastline, Beagle Gulf, Shoal Bay, and the protected waters of Darwin Harbour.',
    canonicalLocationEntityId: 'DARWIN_HARBOUR_CONTEMPORARY',
    temporalContext: 'CONTEMPORARY',
    desktopCamera: {
      latitude: -12.44,
      longitude: 130.77,
      altitudeM: 86000,
      headingDeg: 346,
      pitchDeg: -62,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.45,
      longitude: 130.81,
      altitudeM: 105000,
      headingDeg: 346,
      pitchDeg: -65,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.55,
      longitude: 130.84,
      altitudeM: 130000,
      headingDeg: 346,
      pitchDeg: -65,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.44,
      longitude: 130.78,
      altitudeM: 90000,
      headingDeg: 346,
      pitchDeg: -63,
      rollDeg: 0,
    },
    durationMs: 2200,
    classification: 'ESTABLISHED_FACT',
    confidence: 'VERIFIED',
    notes: 'Contemporary geographic layout of Darwin peninsula and harbour approaches.',
    humanClassification: 'Contemporary Geographic Reality',
    humanConfidence: 'Geodetically Verified',
    sourceInstitutions: ['Australian Hydrographic Office (Chart Aus 26)', 'Geoscience Australia'],
    evidentialNuance: 'Contemporary coastline of Beagle Gulf and Darwin Harbour.',
  },

  STATE_03_WHARF: {
    id: 'STATE_03_WHARF',
    index: 3,
    code: '03',
    label: 'Stokes Hill Wharf',
    geographicScope: 'Darwin Harbour & Historic Wharf Precinct',
    purpose: 'Establish the contemporary physical place from which the visitor experience is presented: Stokes Hill Wharf (12°28\'21"S, 130°50\'55"E). Same wharf. Same sky. Does NOT represent 1942 timber structure footprint.',
    canonicalLocationEntityId: 'STOKES_HILL_WHARF_CONTEMPORARY',
    temporalContext: 'CONTEMPORARY',
    desktopCamera: {
      latitude: -12.4735,
      longitude: 130.8415,
      altitudeM: 3200,
      headingDeg: 338,
      pitchDeg: -44,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4735,
      longitude: 130.8440,
      altitudeM: 3900,
      headingDeg: 338,
      pitchDeg: -47,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4850,
      longitude: 130.8480,
      altitudeM: 4600,
      headingDeg: 338,
      pitchDeg: -48,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4735,
      longitude: 130.8415,
      altitudeM: 3400,
      headingDeg: 338,
      pitchDeg: -44,
      rollDeg: 0,
    },
    durationMs: 2200,
    classification: 'ESTABLISHED_FACT',
    confidence: 'APPROXIMATE',
    notes: 'Contemporary public wharf precinct. Current coordinates must not be inferred as 1942 pier footing.',
    humanClassification: 'Contemporary Orientation Anchor',
    humanConfidence: 'Modern Centroid: Verified · 1942 Timber Footprint: Unresolved',
    sourceInstitutions: ['Australian Hydrographic Office (Chart Aus 26)', 'Darwin Port Authority'],
    evidentialNuance: 'Represents the modern public wharf visitor precinct. The historical 1942 timber wharf was bombed and severed during the raid; its exact engineering footprint and the MV Neptuna explosive breach remain unresolved pending primary railway surveys.',
  },

  /* =========================================================================
   * STAGE 3 — AUTHENTICATED HISTORICAL STORY BEAT CAMERA STATES (BEATS 0 TO 7)
   * Governed by TRUTH, EXPERIENCE & TECHNOLOGY authorities.
   * ========================================================================= */

  BEAT_0_TIMOR_LAUNCH: {
    id: 'BEAT_0_TIMOR_LAUNCH',
    index: 0,
    code: '08:00',
    label: 'Timor Sea Launch Area (Estimated)',
    geographicScope: 'Timor Sea · ~220 NM NNW Darwin',
    purpose: 'Launch window of First Wave (188 aircraft) from IJN 1st Carrier Air Fleet. Broad oceanic perspective looking along transit corridor toward Northern Australia.',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -10.3,
      longitude: 127.8,
      altitudeM: 950000,
      headingDeg: 140,
      pitchDeg: -55,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -10.4,
      longitude: 128.2,
      altitudeM: 1150000,
      headingDeg: 140,
      pitchDeg: -58,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -9.2,
      longitude: 127.8,
      altitudeM: 1400000,
      headingDeg: 140,
      pitchDeg: -58,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -10.3,
      longitude: 127.8,
      altitudeM: 1000000,
      headingDeg: 140,
      pitchDeg: -55,
      rollDeg: 0,
    },
    durationMs: 2600,
    classification: 'RECONSTRUCTION_PARAMETER',
    confidence: 'APPROXIMATE',
    notes: 'Estimated regional launch envelope ~220 NM NNW Darwin. Center point is a mathematical reconstruction parameter for camera composition, not an observed coordinate.',
    humanClassification: 'Reconstruction Parameter (Regional Origin Area)',
    humanConfidence: 'Estimated Regional Envelope (~40km Uncertainty)',
    sourceInstitutions: ['Senshi Sōsho Vol. 26 (Japanese War History Series)', 'IJN 1st Carrier Air Fleet Action Reports', 'Australian War Memorial'],
    evidentialNuance: 'No Allied radar or visual observation sighted the carriers at launch. The regional envelope (~220 NM NNW Darwin) is derived from Japanese carrier records. The center point is an internal mathematical parameter for camera framing, not an observed coordinate.',
    historicalTimestamp: '19 FEB 1942 · 08:00 ACST',
  },

  BEAT_1_BATHURST_WARNING: {
    id: 'BEAT_1_BATHURST_WARNING',
    index: 1,
    code: '09:35',
    label: 'Bathurst Island Warning & Sighting',
    geographicScope: 'Bathurst Island & Clarence Strait',
    purpose: 'Father McGrath sights large formation over Sacred Heart Mission, Nguiu, and radios warning at 09:37. Perspective looks southeast across Clarence Strait.',
    canonicalLocationEntityId: 'BATHURST_ISLAND_MISSION_1942',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -11.65,
      longitude: 130.45,
      altitudeM: 120000,
      headingDeg: 148,
      pitchDeg: -52,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -11.70,
      longitude: 130.52,
      altitudeM: 145000,
      headingDeg: 148,
      pitchDeg: -55,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -11.52,
      longitude: 130.48,
      altitudeM: 175000,
      headingDeg: 148,
      pitchDeg: -56,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -11.65,
      longitude: 130.45,
      altitudeM: 130000,
      headingDeg: 148,
      pitchDeg: -52,
      rollDeg: 0,
    },
    durationMs: 2400,
    classification: 'PRIMARY_SOURCE',
    confidence: 'HIGH',
    notes: 'Mission location verified. Sighting heading 140° confirmed by Lowe Commission Exhibit 3.',
    humanClassification: 'Documented Ground Site & Observed Airspace Corridor',
    humanConfidence: 'Ground Site: Verified · Flight Corridor: Observed Envelope',
    sourceInstitutions: ['Father John McGrath Radio Log (NAA MP401/1)', 'Lowe Royal Commission (1942)', 'RAAF Darwin Operations Record Book'],
    evidentialNuance: 'Sacred Heart Mission at Nguiu is a verified geographic landmark. Father McGrath radioed the warning at 09:37 via the coastal radio service. The attacking formation passed high overhead heading southeast (~140°); its flight corridor is an observed broad band, not a satellite-tracked individual aircraft path.',
    historicalTimestamp: '19 FEB 1942 · 09:35 ACST',
  },

  BEAT_2_HARBOUR_STRIKE: {
    id: 'BEAT_2_HARBOUR_STRIKE',
    index: 2,
    code: '09:58',
    label: 'First Bombs Fall on Harbour & Town',
    geographicScope: 'Darwin Harbour & Town Peninsula',
    purpose: 'Coordinated first wave attack ingress along 315°–345° axis from southeast out of the rising sun. First detonations at 09:58.',
    canonicalLocationEntityId: 'DARWIN_HARBOUR_CONTEMPORARY',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -12.4650,
      longitude: 130.8350,
      altitudeM: 22000,
      headingDeg: 328,
      pitchDeg: -46,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4660,
      longitude: 130.8380,
      altitudeM: 26000,
      headingDeg: 328,
      pitchDeg: -48,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4920,
      longitude: 130.8450,
      altitudeM: 34000,
      headingDeg: 328,
      pitchDeg: -50,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4650,
      longitude: 130.8350,
      altitudeM: 23500,
      headingDeg: 328,
      pitchDeg: -46,
      rollDeg: 0,
    },
    durationMs: 2200,
    classification: 'ESTABLISHED_FACT',
    confidence: 'VERIFIED',
    notes: 'Attack axis aligned with Lowe Commission findings and Senshi Sōsho attack plans.',
    humanClassification: 'Established Historical Event & Documented Target Sector',
    humanConfidence: 'Target Area: Verified · Ingress Axis: Documented (315°–345°)',
    sourceInstitutions: ['Lowe Commission (1942)', 'RAN Official History (Gill Vol. 1)', 'Australian War Memorial Operations Record'],
    evidentialNuance: 'First bombs impacted the harbour roadstead and town peninsula at 09:58 ACST. Attack axis 315°–345° is verified from multiple ship logs and shore battery observations. 1942 timber wharf geometry remains unresolved.',
    historicalTimestamp: '19 FEB 1942 · 09:58 ACST',
  },

  BEAT_3_POST_OFFICE: {
    id: 'BEAT_3_POST_OFFICE',
    index: 3,
    code: '10:00',
    label: 'Post Office Trench Direct Hit',
    geographicScope: 'Darwin Civic Precinct · Mitchell & Bennett Sts',
    purpose: 'Direct bomb hit on open civilian trench behind Darwin Post and Telegraph Office, killing 9 civilians. Restrained civic perspective.',
    canonicalLocationEntityId: 'DARWIN_POST_OFFICE_1942',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -12.4660,
      longitude: 130.8405,
      altitudeM: 4200,
      headingDeg: 32,
      pitchDeg: -54,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4665,
      longitude: 130.8415,
      altitudeM: 4800,
      headingDeg: 32,
      pitchDeg: -56,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4765,
      longitude: 130.8430,
      altitudeM: 5800,
      headingDeg: 32,
      pitchDeg: -54,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4660,
      longitude: 130.8405,
      altitudeM: 4400,
      headingDeg: 32,
      pitchDeg: -54,
      rollDeg: 0,
    },
    durationMs: 2000,
    classification: 'ESTABLISHED_FACT',
    confidence: 'HIGH',
    notes: 'Verified civic location. CWGC and Lowe Commission records confirm nine fatalities.',
    humanClassification: 'Established Civic Site & Documented Bomb Casualty',
    humanConfidence: 'Verified Ground Site · Verified Fatality Record',
    sourceInstitutions: ['Commonwealth War Graves Commission (CWGC)', 'Lowe Commission Exhibit 12', 'National Archives of Australia Series A816'],
    evidentialNuance: 'Corner of Mitchell and Bennett Streets. Struck by a direct bomb hit on an open trench shelter behind the building at approx 10:00 ACST, killing 9 civilians (Postmaster H.A. Shugg’s family, telephonists, and postal supervisors).',
    historicalTimestamp: '19 FEB 1942 · 10:00 ACST',
  },

  BEAT_4_PEARY_ATTACK: {
    id: 'BEAT_4_PEARY_ATTACK',
    index: 4,
    code: '10:45',
    label: 'USS Peary Under Sustained Attack in Channel',
    geographicScope: 'Darwin Harbour Main Channel',
    purpose: 'USS Peary (DD-226) conducts violent evasive manoeuvres under repeated dive-bombing attacks in mid-harbour; struck by 5 bombs.',
    canonicalLocationEntityId: 'DARWIN_HARBOUR_CONTEMPORARY',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -12.4760,
      longitude: 130.8240,
      altitudeM: 5500,
      headingDeg: 42,
      pitchDeg: -45,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4765,
      longitude: 130.8260,
      altitudeM: 6200,
      headingDeg: 42,
      pitchDeg: -48,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4890,
      longitude: 130.8280,
      altitudeM: 7600,
      headingDeg: 42,
      pitchDeg: -50,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4760,
      longitude: 130.8240,
      altitudeM: 5800,
      headingDeg: 42,
      pitchDeg: -45,
      rollDeg: 0,
    },
    durationMs: 2200,
    classification: 'HISTORICAL_INTERPRETATION',
    confidence: 'APPROXIMATE',
    notes: 'Underway combat area in harbour channel recorded in DANFS and RAN Official History.',
    humanClassification: 'Historical Action Area & Underway Combat Sector',
    humanConfidence: 'Channel Sector: Documented · Instantaneous Positions: Approximate',
    sourceInstitutions: ['Dictionary of American Naval Fighting Ships (DANFS)', 'RAN Official History (Gill Vol. 1)', 'USS Peary Action Summaries'],
    evidentialNuance: 'USS Peary (DD-226) was not anchored or stationary; she was underway executing continuous high-speed evasive manoeuvres throughout the channel while fighting dive-bombers. The displayed sector represents the manoeuvre zone, not a single point of impact.',
    historicalTimestamp: '19 FEB 1942 · 10:15–10:45 ACST',
  },

  BEAT_5_RAAF_AIRFIELD: {
    id: 'BEAT_5_RAAF_AIRFIELD',
    index: 5,
    code: '12:00',
    label: 'Second Wave Strike on RAAF Station Darwin',
    geographicScope: 'RAAF Station Darwin & Parap Aerodrome',
    purpose: 'Fifty-four twin-engine land bombers from Kendari and Ambon arrive from northwest at 18,000–23,000 ft, pattern-bombing military runways and hangars.',
    canonicalLocationEntityId: 'RAAF_STATION_DARWIN_1942',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -12.4200,
      longitude: 130.8620,
      altitudeM: 34000,
      headingDeg: 315,
      pitchDeg: -50,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4220,
      longitude: 130.8660,
      altitudeM: 39000,
      headingDeg: 315,
      pitchDeg: -52,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4440,
      longitude: 130.8760,
      altitudeM: 48000,
      headingDeg: 315,
      pitchDeg: -54,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4200,
      longitude: 130.8620,
      altitudeM: 36000,
      headingDeg: 315,
      pitchDeg: -50,
      rollDeg: 0,
    },
    durationMs: 2400,
    classification: 'ESTABLISHED_FACT',
    confidence: 'HIGH',
    notes: '14th Heavy AA Battery tracking plots record arrival from Beagle Gulf at approx 11:58.',
    humanClassification: 'Documented Military Installation & Observed Ingress Vector',
    humanConfidence: 'Airfield Base: Verified · Approach Axis: Documented',
    sourceInstitutions: ['RAAF Station Darwin Operations Record Book', '14th Heavy AA Battery Tracking Logs', 'Senshi Sōsho Vol. 26'],
    evidentialNuance: 'Second wave of 54 twin-engine naval land bombers (from Kendari and Ambon) struck from 18,000–23,000 ft at 12:00 ACST. Airfield marker denotes the historical military airfield perimeter centroid, not a single target building.',
    historicalTimestamp: '19 FEB 1942 · 12:00 ACST',
  },

  BEAT_6_PEARY_LOST: {
    id: 'BEAT_6_PEARY_LOST',
    index: 6,
    code: '13:00',
    label: 'USS Peary Modern Surveyed Wreck Position',
    geographicScope: 'Darwin Harbour Channel · 27m Depth',
    purpose: 'USS Peary sinks stern-first at approx 13:00; 91 crew lost, the heaviest single loss of American life in Australian waters. Somber close composition above surveyed war grave position.',
    canonicalLocationEntityId: 'DARWIN_HARBOUR_CONTEMPORARY',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -12.4765,
      longitude: 130.8245,
      altitudeM: 2800,
      headingDeg: 20,
      pitchDeg: -42,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4770,
      longitude: 130.8260,
      altitudeM: 3300,
      headingDeg: 20,
      pitchDeg: -45,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4865,
      longitude: 130.8270,
      altitudeM: 3800,
      headingDeg: 20,
      pitchDeg: -46,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4765,
      longitude: 130.8245,
      altitudeM: 3000,
      headingDeg: 20,
      pitchDeg: -42,
      rollDeg: 0,
    },
    durationMs: 2000,
    classification: 'MODERN_SURVEYED_WRECK_POSITION',
    confidence: 'HIGH',
    notes: 'Surveyed wreck coordinates confirmed by Australian Hydrographic Office Chart Aus 26.',
    humanClassification: 'Modern Surveyed Wreck Position & Protected War Grave',
    humanConfidence: 'Surveyed Seabed Site: Verified · Surface Sinking Point: Approximate',
    sourceInstitutions: ['Australian Hydrographic Office (Chart Aus 26)', 'Northern Territory Heritage Register', 'US Navy Memorial Records'],
    evidentialNuance: 'The displayed coordinate is the modern hydrographically surveyed seabed wreck site at 27m depth, which is a legally protected historic shipwreck and war grave. The surface sinking location (~13:00 ACST) occurred nearby in the channel; seabed resting position reflects post-impact descent and tidal drift. 91 crew lost.',
    historicalTimestamp: '19 FEB 1942 · 13:00 ACST',
  },

  BEAT_7_RECKONING: {
    id: 'BEAT_7_RECKONING',
    index: 7,
    code: 'Dusk',
    label: 'The Reckoning · Contemporary Stokes Hill Wharf',
    geographicScope: 'Stokes Hill Wharf & Darwin Harbour Waters',
    purpose: 'Dusk falls over the devastated harbour. Fires burn into the night. Multi-source death toll 235 to 250+. Reflective evening composition returning visitor to the contemporary wharf.',
    canonicalLocationEntityId: 'STOKES_HILL_WHARF_CONTEMPORARY',
    temporalContext: 'HISTORICAL_1942',
    desktopCamera: {
      latitude: -12.4735,
      longitude: 130.8420,
      altitudeM: 4800,
      headingDeg: 305,
      pitchDeg: -40,
      rollDeg: 0,
    },
    tabletCamera: {
      latitude: -12.4740,
      longitude: 130.8445,
      altitudeM: 5500,
      headingDeg: 305,
      pitchDeg: -43,
      rollDeg: 0,
    },
    mobilePortraitCamera: {
      latitude: -12.4860,
      longitude: 130.8480,
      altitudeM: 6800,
      headingDeg: 305,
      pitchDeg: -46,
      rollDeg: 0,
    },
    mobileLandscapeCamera: {
      latitude: -12.4735,
      longitude: 130.8420,
      altitudeM: 5100,
      headingDeg: 305,
      pitchDeg: -40,
      rollDeg: 0,
    },
    durationMs: 2600,
    classification: 'HISTORICAL_INTERPRETATION',
    confidence: 'HIGH',
    notes: 'Same wharf. Same sky. Returns the visitor to the contemporary orientation anchor.',
    humanClassification: 'Contemporary Orientation Precinct & Historical Synthesis',
    humanConfidence: 'Contemporary Wharf: Verified · 1942 Timber Footprint: Unresolved',
    sourceInstitutions: ['Australian War Memorial Canon', 'Lowe Commission (1942)', 'Geoscience Australia'],
    evidentialNuance: 'Contemporary Stokes Hill Wharf provides the spatial anchor for the visitor ("Same wharf. Same sky."). The exact 1942 timber wharf geometry, cargo shed alignment, and MV Neptuna explosive breach remain unresolved and require primary Commonwealth Railways engineering surveys.',
    historicalTimestamp: '19 FEB 1942 · Dusk',
  },
};

export const ORDERED_DEMO_STATE_IDS: SpatialDemonstrationStateId[] = [
  'STATE_00_WORLD',
  'STATE_01_NORTH',
  'STATE_02_DARWIN',
  'STATE_03_WHARF',
];

export const ORDERED_BEAT_STATE_IDS: SpatialDemonstrationStateId[] = [
  'BEAT_0_TIMOR_LAUNCH',
  'BEAT_1_BATHURST_WARNING',
  'BEAT_2_HARBOUR_STRIKE',
  'BEAT_3_POST_OFFICE',
  'BEAT_4_PEARY_ATTACK',
  'BEAT_5_RAAF_AIRFIELD',
  'BEAT_6_PEARY_LOST',
  'BEAT_7_RECKONING',
];

/**
 * Mapping from timeline beat index (-1 for pre-timeline) to spatial state.
 * Direct beat-governed resolution for Beats 0 through 7.
 */
export function mapBeatIndexToDemoState(beatIndex: number): SpatialDemonstrationStateId {
  switch (beatIndex) {
    case 0: return 'BEAT_0_TIMOR_LAUNCH';
    case 1: return 'BEAT_1_BATHURST_WARNING';
    case 2: return 'BEAT_2_HARBOUR_STRIKE';
    case 3: return 'BEAT_3_POST_OFFICE';
    case 4: return 'BEAT_4_PEARY_ATTACK';
    case 5: return 'BEAT_5_RAAF_AIRFIELD';
    case 6: return 'BEAT_6_PEARY_LOST';
    case 7: return 'BEAT_7_RECKONING';
    default:
      if (beatIndex < 0) return 'STATE_00_WORLD';
      return 'STATE_03_WHARF';
  }
}
